config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Session controller routes for login and logout
  post 'home/login'
  get 'home/logout'

  root 'home#index'

  # Routes for Customers(users)
  get '/customers' => 'users#index'
  get '/customers/new' => 'users#new'
  post '/customers' => 'users#create'
  get '/customers/:id' => 'users#show'
  get '/customers/edit/:id' => 'users#edit'
  patch '/customers/:id' => 'users#update'
  delete '/customers/:id' => 'users#destroy'
  get '/customers', :controller => :users, :action => :index, :page => 1

  # Routes for Bulk Uploads
  get '/bulk_uploads/customers'
  get '/bulk_uploads/credit_cards'
  get '/bulk_uploads/transactions'
  post '/bulk_uploads/upload' => 'bulk_uploads#upload'

  # Resourceful Routes
  resources :users
  resources :transactions
  resources :statements
  resources :bulk_uploads
  resources :credit_cards

  # temp route to create admin
  get '/create_admin' => 'users#create_admin'

  # Other utility routes
  get '/find_geographic/:zip_code' => 'users#find_geographic'
  get '/find_states/:country' => 'users#get_states_from_country'
  get '/find_cities/:state' => 'users#get_cities_from_state'
  post '/customers/filter' => 'users#filter_values'
  get 'credit_cards_of_user/:user_id' => 'credit_cards#user_credit_cards'
  # post '/sort' => 'datatables#sort_array'
  post '/filter' => 'datatables#sort_array'

  get '/generate_customer_id' => 'migration#generate_customer_id'

  post '/upload/file' => 'users#file_upload'

  get '/pdf' => 'statements#create_statement_template'
end

app/models/user.rb
class User < ActiveRecord::Base
  # to use text search
  include PgSearch

  pg_search_scope :search,
                  :against => [:id ,:first_name, :last_name, :email, :phone_number, :date_of_birth],
                  :using => {:tsearch => {:dictionary => "english", :prefix => true}},
                  :associated_against => {credit_cards: [:card_number, :credit_limit, :available_credit_limit]}

  # Associations
  has_one :address, :dependent => :destroy
  has_many :credit_cards, :dependent => :destroy
  has_many :transactions, :dependent => :destroy
  has_many :statements, :dependent => :destroy
  has_many :bulk_uploads, :dependent => :destroy

  # Accept Nested Attributes for user
  accepts_nested_attributes_for :credit_cards, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true

  # Authentication
  has_secure_password

  # Required fields validations
  validates_presence_of :first_name, :last_name, :email, :date_of_birth, :phone_number
  validates_uniqueness_of :email

  # custom validations
  validate :validate_date_of_birth

  def validate_date_of_birth
    errors.add(:date_of_birth, 'cannot be in the future') if
        !date_of_birth.blank? and date_of_birth > Date.today
  end

  # Callbacks
  after_initialize :add_role

  # set role as customer to user
  def add_role
    self.role = 'customer'
  end

  # get the full name of the user
  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  # get the display name of user
  def display_name
    "#{self.last_name}, #{self.first_name}"
  end

  # get the profile pic url
  def profile_pic_url
    $BUCKET.object(self.profile_pic_path).presigned_url(:get)
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      default_scoped
    end
  end

  # Get all customers
  def self.customers
    where(role: 'customer')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  helper_method :sort_column, :sort_direction
  layout nil, only: [:new, :edit]


  # action for customers home page
  def index
    @customers = User.text_search(query).customers.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page])
    respond_to do |format|
      format.js
      format.html
      format.json { render :json => @customers }
    end
    
  end

  # action for adding new customer
  def new
    @customer = User.new
    @customer.build_address
    @customer.credit_cards.build
    render 'users/new', :layout => nil
  end

  # action to create new customer
  def create
    if (customer_params[:address_attributes][:geographic_id].blank?)
      geographic = Geographic.create(geographic_params)
      if geographic.save!
        customer_params[:address_attributes][:geographic_id] = geographic.id
      end
    end
       @customer = User.create(customer_params)
      if @customer.save
        Rails.logger.info "Customer created successfully with id #{@customer.id}"
        # Sign up email will be sent to user on sign up
        # CustomerMailer.account_creation_notification(@customer, customer_params[:password])
        render :text => 'success'
      else
        @geographic = !@customer.address.geographic_id.nil? ? Geographic.find(@customer.address.geographic_id) : nil
        Rails.logger.info 'Unable to save the customer'
        render :new, layout: nil
      end
  end

  # action to edit the customer
  def edit
    @customer = get_customer(params[:id])
    @customer.build_address if @customer.address.nil?
    @customer.credit_cards.build if @customer.credit_cards.nil?
    @geographic = !@customer.address.geographic_id.nil? ? Geographic.find(@customer.address.geographic_id) : nil
    render 'users/edit', layout: nil
  end

  # action to update the customer
  def update
    @customer = User.find(params[:id])
    if customer_params[:address_attributes][:geographic_id].blank? && !geographic_params.blank?
      geographic = Geographic.create(geographic_params)
      if geographic.update_attributes!(geographic_params)
        customer_params[:address_attributes][:geographic_id] = geographic.id
      end
    end
    key = "#{AWS_CONFIG['default_key']}/#{@customer.id}/#{session[:file_name]}"
    if !session[:file_name].blank?
      @customer.profile_pic_path = key
    end
    if @customer.update_attributes(customer_params)
      Thread.new do
          begin
            if !session[:file_name].blank?
              file_path = "#{Rails.root}/public/#{session[:file_name]}"
              if File.exists?(file_path)
                object = $BUCKET.object(key)
                object.put(
                    :body => File.open(file_path)
                )
              end
            end
             Rails.logger.info "Customer details updated successfully for customer with id #{@customer.id}"
          rescue
            Rails.logger.error "Errors occured while uploading profile pic for customer with id #{@customer.id}"
          end
      end
      # File.delete("#{Rails.root}/public/#{session[:file_name]}") if File.exists?("#{Rails.root}/public/#{session[:file_name]}")
      render :text => 'success'
    else
      @geographic = !@customer.address.geographic_id.nil? ? Geographic.find(@customer.address.geographic_id) : nil
      render :edit, layout: nil
    end
  end

  def destroy
    @customer = get_customer(params[:id])
    if @customer.destroy!
      render :index
    end
  end

  def find_geographic
    geographic = Geographic.find_by_zip_code(params[:zip_code])
    if !geographic.nil?
      render :json => geographic
    else
      render :nothing => true
    end
  end

  def get_states_from_country
    geographics = Geographic.select(:state).where(:country => params[:country]).uniq
    if !geographics.nil?
      render :json => geographics
    else
      render :nothing => true
    end
  end

  def get_cities_from_state
    geographics = Geographic.select(:city).where(:state => params[:state]).uniq
    if !geographics.nil?
      render :json => geographics
    else
      render :nothing => true
    end
  end

  def file_upload
    file = params[:file]
    case file.content_type
      when "image/jpeg"
        file_name = "profile_pic.jpg"
      when "image/png"
        file_name = "profile_pic.png"
      when "image/gif"
        file_name = "profile_pic.gif"
      when "image/bmp"
        file_name = "profile_pic.bmp"
    end
    file_path = "#{Rails.root}/public/#{file_name}"
    File.open(file_path, "wb") do |f|
      f.write file.read
    end

    if(File.exists?(file_path))
      if(!file_name.blank?)
        session[:file_name] = file_name
      end
    end

    render :text => file
  end

  private

  def customer_params
    params.require(:user).permit(
        :email,
        :password,
        :first_name,
        :last_name,
        :phone_number,
        :date_of_birth,
        :profile_pic_path,
        address_attributes: [
            :id,
            :user_id ,
            :geographic_id,
            :house_name,
            :street,
            :area
        ],
        credit_cards_attributes: [
            :id,
            :user_id,
            :card_number,
            :name_on_card,
            :valid_from_date,
            :valid_to_date,
            :cvv,
            :credit_limit,
            :available_credit_limit,
            :statement_date,
            :_destroy
        ]
    )
  end

  def geographic_params
    params.require(:geographic).permit(
        :zip_code,
        :country,
        :state,
        :city
    )
  end

  def get_customer(id)
    User.find(id)
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def query
    params[:search].present? ? params[:search] : ""
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_customers.html.erb
<% if @customers.present? %>
  <table class="table table-hover table-responsive table-condensed pretty" style="background-color:#fff;text-align:center;">
    <tr>
      <th>
        <%= sortable "id",t('user.id') %>
      </th>
      <th>
        <%= sortable "first_name",t('user.first_name') %>
      </th>
      <th>
        <%= sortable "last_name",t('user.last_name') %>
      </th>
      <th>
        <%= sortable "email",t('user.email') %>
      </th>
      <th>
        <%= sortable "phone_number",t('user.phone_number') %>
      </th>
      <th>
        <%= t('credit_card.ccn') %>
      </th>
      <th>
        <%= t('credit_card.cl') %>
      </th>
      <th>
        <%= t('credit_card.acl') %>
      </th>
      <th colspan="2">
        <%= t('views.actions') %>
      </th>
    </tr>
    <% @customers.each do |customer| %>
      <tr>
        <td>
          <%= customer.id %>
        </td>
        <td>
          <%= customer.first_name %>
        </td>
        <td>
          <%= customer.last_name %>
        </td>
        <td>
          <%= customer.email %>
        </td>
        <td>
          <%= customer.phone_number %>
        </td>
        <td colspan="3">
          <%= render 'shared/credit_card_display', :credit_cards => customer.credit_cards %>
        </td>
        <td>
          <div>
            <button class="btn btn-primary btn-sm btn-edit-customer" customer_id="<%= customer.id %>" data-target="#customerModal" data-toggle="modal" onclick="editCustomer(<%= customer.id %>)">Edit</button>
            <button class="btn btn-danger btn-sm btn-delete-customer" onclick="deleteCustomer(<%= customer.id %>,event)">Delete</button>
          </div>
        </td>
      </tr>
    <% end %>
    <tr>
      <th>
        <%= sortable "id",t('user.customer_id') %>
      </th>
      <th>
        <%= sortable "first_name",t('user.first_name') %>
      </th>
      <th>
        <%= sortable "last_name",t('user.last_name') %>
      </th>
      <th>
        <%= sortable "email",t('user.email') %>
      </th>
      <th>
        <%= sortable "phone_number",t('user.phone_number') %>
      </th>
      <th>
        <%= t('credit_card.ccn') %>
      </th>
      <th>
        <%= t('credit_card.cl') %>
      </th>
      <th>
        <%= t('credit_card.acl') %>
      </th>
      <th colspan="2">
        <%= t('views.actions') %>
      </th>
    </tr>
  </table>
  <%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
<% else %>
  <h3>
    <%= t('messages.no_records') %>
  </h3>
<% end %>
<script>
  
  $(function(){
       // to handle pagination and sorting
       $("#customers th a,#customers .pagination a").on("click",function(e){
              $.getScript(this.href);
              e.preventDefault();
        });
       $(document).ready(function (argument) {
          $('.credit_card_number').inputmask("9999-9999-9999-9999");
          $('.cvv').inputmask("999");
       });
  });


</script>

app/views/users/_form.html.erb
<div class="modal-body">
  <% if @customer.errors.any? %>
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= pluralize(@customer.errors.count, "error") + " prohibited this customer from being saved:" %>
        </h3>
      </div>
      <div class="panel-body">
        <% @customer.errors.full_messages.each do |msg| %>
          <p class="alert alert-danger">
            <%= msg %>
          </p>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group" id="profilePic">
        <img class="img-thumbnail profilePicture" src="<%= @customer.profile_pic_path.blank? ? t('user.placeholder_pic') : @customer.profile_pic_url %>"/>
        <input id="userPhoto" style="display:none;" type="file"></input>
      </div>
      <br/>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= t('form_labels.basic_details') %>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <%= f.text_field :first_name,{:class => 'form-control',:placeholder => t('user.first_name'), :required => true} %>
            <%= f.text_field :last_name,{:class => 'form-control',:placeholder => t('user.last_name'), :required => true} %>
            <%= f.text_field :date_of_birth,{:class => 'form-control datepicker',:placeholder => t('user.date_of_birth'), :required => true} %>
            <%= f.hidden_field :password %>
            <%= f.email_field :email,{:class => 'form-control',:placeholder => t('user.email') , :required => true} %>
            <%= f.phone_field :phone_number,{:class => 'form-control phone_number',:placeholder => t('user.phone_number'), :required => true} %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('form_labels.address_details') %>
    </div>
    <div class="panel-body">
      <%= f.fields_for :address do |address| %>
        <%= render 'shared/address', :address => address %>
      <% end %>
    </div>
  </div>
  <br/>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('form_labels.credit_card_details') %>
    </div>
    <div class="panel-body">
      <%= f.fields_for :credit_cards do |credit_card| %>
        <%= render 'shared/credit_card', :credit_card => credit_card %>
      <% end %>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
  <%= f.submit t('buttons.save_customer'),{:class => 'btn btn-success'} %>
</div>
<div id="progress">
  <div class="bar" style="width:0%"></div>
</div>
<script>
  
  $(function(){

    $(document).ready(function(){
        $('.datepicker').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true
        });
        $('.phone_number').inputmask("(999) 999-9999");
    });

    $("#profilePic img").click(function(){
      $("#userPhoto").click();
    });

    $("#userPhoto").change(function(e){
        e.preventDefault();
        var selectedFileContent;
        var myFormData = new FormData();
        var file = e.target.files[0];
        myFormData.append('file',file);
          var url = window.location.origin + '/upload/file';
          $.ajax({
            url: url,
            data: myFormData,
            processData: false,
            contentType: false,
            type: 'POST'
          }).success(function(response){
              //console.log(response);
          });
        console.log(myFormData);
    });

  // submit the add and edit form through ajax
  $(".user-form").submit(function(e){
    $.post($(".user-form").attr("action"), $(".user-form").serialize(), function(response){
      $("#modal-data").html("<img class='loading-icon' src='/images/loading-icon.gif'><h3 class='align-center'>Please wait...</h3>");
      if(response == 'success'){
          $.get($("#customers_search").attr("action"), $("#customers_search").serialize(), null, "script");
          $('#customerModal').modal("hide");
      }else{
          $('#modal-data').html(response);
      }
    });
    e.preventDefault();
  });

  var origin = window.location.origin;
  // function to auto fill country, state and city based on the zip code
  $('#geographic_zip_code').blur(function(e){
          var zipCode = $('#geographic_zip_code').val().trim();
          var url = origin + '/find_geographic/' + zipCode;
          if(zipCode){
              $.ajax({
                  url: url,
                  type: 'get'
              }).success(function(response){
                  if(response){
                      $('#user_address_attributes_geographic_id').val(response.id);
                      $('#geographic_country').val(response.country);
                      $('#geographic_state').val(response.state);
                      $('#geographic_city').val(response.city);
                  }
              });
          }else{
            $('#geographic_country').val("");
            $('#geographic_state').val("");
            $('#geographic_city').val("");
          }
      });

      // function to populate the states based on the selected country
      $('#geographic_country').change(function(e){
          var country =$('#geographic_country').val();
          if(country){
            var url = origin + '/find_states/' + country;
            $.ajax({
                url: url,
                type: 'get'
            }).success(function(response){
                if(response){
                    $('#geographic_state option[value!=""]').remove();
                    $('#geographic_city option[value!=""]').remove();
                    for(var i=0;i< response.length;i++){
                        $("#geographic_state").append(new Option(response[i].state, response[i].state));
                    }
                }
            });
          }
      });

      // function to populate cities based on the selected state
      $('#geographic_state').change(function(e){
          var state =$('#geographic_state').val();
          if(state){
            var url = origin + '/find_cities/' + state;
            $.ajax({
                url: url,
                type: 'get'
            }).success(function(response){
                if(response){
                    $('#geographic_city option[value!=""]').remove();
                    for(var i=0;i< response.length;i++){
                        $("#geographic_city").append(new Option(response[i].city, response[i].city));
                    }
                }
            });
         }
      });
  });

</script>

app/views/users/_user_table_view.html.erb
<table class="table table-responsive table-condensed table-hover table-bordered">
  <% customers.each do |customer| %>
    <tr>
      <td>
        <%= customer.customer_id %>
      </td>
      <td>
        <%= customer.first_name %>
      </td>
      <td>
        <%= customer.last_name %>
      </td>
      <td>
        <%= customer.email %>
      </td>
      <td>
        <%= customer.phone_number %>
      </td>
      <td>
        <%= render 'shared/credit_card_display', :credit_cards => customer.credit_cards %>
      </td>
      <td>
        <div>
          <button class="btn btn-default btn-xs btn-edit-customer" customer_id="<%= customer.id %>" data-target="#customerModal" data-toggle="modal" onclick="editCustomer(<%= customer.id %>)">Edit</button>
          <%= link_to 'Delete',  user_path(customer.id), :method => :delete, :data => { confirm: 'Are you sure you want to delete this customer?' }, class: 'btn btn-danger btn-xs' %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<%= form_for @customer,:url => {:controller => 'users' , :action => :update},html: {:class => 'form-inline user-form'} do |f| %>
  <%= render 'users/form', :f => f %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-8">
    <button class="btn btn-default" data-target="#customerModal" data-toggle="modal" id="add_customer">+ Add Customer</button>
    <button class="btn btn-default" data-target="#addCreditCardToCustomer" data-toggle="modal" id="add_credit_card_to_customer">+ Add Credit Card To Customer</button>
  </div>
</div>
<%= form_tag users_path, :method => :get, :id => 'customers_search', :class => 'search-form' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <label>Search:</label>
  <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Anything...' %>
<% end %>
<div id="customers">
  <%= render 'users/customers' %>
</div>
<div class="modal fade" id="customerModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" class="close" data-dismiss="modal" type="button">
          <span aria-hidden="true">
            &times;
          </span>
        </button>
        <h3 class="modal-title"></h3>
      </div>
      <div id="modal-data"></div>
    </div>
  </div>
</div>
<div class="modal fade" id="addCreditCardToCustomer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" class="close" data-dismiss="modal" type="button">
          <span aria-hidden="true">
            &times;
          </span>
        </button>
        <h3 class="modal-title">Add Credit Card To Customer</h3>
      </div>
      <div id="credit-card-model-data"></div>
    </div>
  </div>
</div>
<script>
  
  // global variables
  var origin = window.location.origin;
  $(function () {
      // function to get the add customer form using the ajax call
      $('#add_customer').click(function(){
          var url = origin + '/customers/new';
          $.ajax({
              url: url,
              type: 'get'
          }).success(function(response){
              $('#modal-data').html(response);
              $('#customerModal .modal-title').html('Add Customer');
              $("#user_password").val("#{SecureRandom.hex(8)}");
          });
      });
      // function to get the add credit card to customer form using ajax
      $("#add_credit_card_to_customer").click(function(e){
        var url = origin + '/credit_cards/new';
        $.ajax({
            url: url,
            type: 'get'
        }).success(function(response){
            $('#credit-card-model-data').html(response);
        });
      });
      // function to handle searching on the customers data-tables
      $("#customers_search .form-control").keyup(function(e){
          $.get($("#customers_search").attr("action"), $("#customers_search").serialize(), null, "script");
          e.preventDefault();
      });
  });
  // function to get the edit customer form using the ajax call
  function editCustomer(customer_id){
      var url = origin + '/customers/edit/'+ customer_id;
      $.ajax({
          url: url,
          type: 'get'
      }).success(function(response){
          $('#modal-data').html(response);
          $('#customerModal .modal-title').html('Edit Customer');
      });
  }

  // function to delete the customer using the ajax call
  function deleteCustomer(customer_id,e){
      //console.log(e.target);
      var selectedCustomer = e.target.parentNode.parentNode.parentNode;
      var confirmation = confirm('Are you sure you want to delete this customer?');
      if(confirmation == true){
        $(selectedCustomer).hide("fast");
        var url = origin + '/customers/'+ customer_id;
              $.ajax({
                  url: url,
                  type: 'delete'
              }).success(function(response){
                  $.get($("#customers_search").attr("action"), $("#customers_search").serialize(), null, "script");
              });
      }
  }

</script>

app/views/users/index.js.erb
$("#customers").html("<%= escape_javascript(render "users/customers") %>");

app/views/users/new.html.erb
<%= form_for @customer,:url => {:controller => 'users', :action => :create},html: {:class => 'form-inline user-form'} do |f| %>
  <%= render 'users/form', :f => f %>
<% end %>