config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Session controller routes for login and logout
  post 'home/login'
  get 'home/logout'

  root 'home#index'

  # Routes for Customers(users)
  get '/customers' => 'users#index'
  get '/customers/new' => 'users#new'
  post '/customers' => 'users#create'
  get '/customers/:id' => 'users#show'
  get '/customers/edit/:id' => 'users#edit'
  patch '/customers/:id' => 'users#update'
  delete '/customers/:id' => 'users#destroy'
  get '/customers', :controller => :users, :action => :index, :page => 1

  # Routes for Bulk Uploads
  get '/bulk_uploads/customers'
  get '/bulk_uploads/credit_cards'
  get '/bulk_uploads/transactions'
  post '/bulk_uploads/upload' => 'bulk_uploads#upload'

  # Resourceful Routes
  resources :users
  resources :transactions
  resources :statements
  resources :bulk_uploads
  resources :credit_cards

  # temp route to create admin
  get '/create_admin' => 'users#create_admin'

  # Other utility routes
  get '/find_geographic/:zip_code' => 'users#find_geographic'
  get '/find_states/:country' => 'users#get_states_from_country'
  get '/find_cities/:state' => 'users#get_cities_from_state'
  post '/customers/filter' => 'users#filter_values'
  get 'credit_cards_of_user/:user_id' => 'credit_cards#user_credit_cards'
  # post '/sort' => 'datatables#sort_array'
  post '/filter' => 'datatables#sort_array'

  get '/generate_customer_id' => 'migration#generate_customer_id'

  post '/upload/file' => 'users#file_upload'

  get '/pdf' => 'statements#create_statement_template'
end

app/views/shared/_address.html.erb
<div class="form-group">
  <%= address.text_field :house_name,{:class => 'form-control',:placeholder => 'House Name', :required => true} %>
  <%= address.text_field :street,{:class => 'form-control',:placeholder => 'Street', :required => true} %>
  <%= address.text_field :area,{:class => 'form-control',:placeholder => 'Area', :required => true} %>
  <%= address.hidden_field :geographic_id %>
  <%= fields_for :geographic do |geographic| %>
    <%= render 'shared/geographic',:geographic => geographic %>
  <% end %>
</div>

app/views/shared/_credit_card.html.erb
<div class="panel panel-info" style="margin-top:10px">
	<div class="panel-body">
		<div class="form-group">
			<%= credit_card.text_field :card_number,{:class => 'form-control credit_card_number',:placeholder => t('credit_card.number'), :required => true} %>
			<%= credit_card.text_field :name_on_card,{:class => 'form-control',:placeholder => t('credit_card.name'), :required => true} %>
			<%= credit_card.text_field :cvv,{:class => 'form-control cvv',:placeholder => t('credit_card.cvv')} %>
			<%= credit_card.text_field :credit_limit,{:class => 'form-control amount',:placeholder => 'Credit Limit', :required => true} %>
			<br/>
			<%= credit_card.text_field :statement_date,{:class => 'form-control datepicker',:placeholder => t('credit_card.statementDate'), :required => true, :style => 'margin-bottom:0;'} %>
			<div class="input-daterange input-group">
				<%= credit_card.text_field :valid_from_date,{:class => 'form-control datepicker',:placeholder => t('credit_card.validFrom'), :required => true} %>
				<span class="input-group-addon">to</span>
				<%= credit_card.text_field :valid_to_date,{:class => 'form-control datepicker',:placeholder => t('credit_card.validTo'), :required => true} %>
			</div>
		</div>
	</div>
	<% #.panel-footer.credit_card_destroy %>
	<% #  .form-group %>
	<% #    = credit_card.check_box :_destroy %>
	<% #    = credit_card.label :_destroy, "Remove this Credit Card" %>
</div>

app/views/shared/_credit_card_display.html.erb
<table class="table table-responsive table-bordered table-condensed credit-card-table" style="border:none !important;">
  <% credit_cards.each do |card| %>
    <tr>
      <td>
        <%= card.card_number %>
      </td>
      <td>
        <%= number_to_currency(card.credit_limit, :unit => '₹.') %>
      </td>
      <td>
        <%= number_to_currency(card.available_credit_limit, :unit => '₹.') %>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/_geographic.html.erb
<%= geographic.text_field :zip_code,{:class => 'form-control',:placeholder => 'Zip Code', :required => true} %>
<div class="form-group">
  <%= geographic.collection_select(:country, Geographic.select(:country).uniq, :country, :country, {:include_blank => "Select Country"}, {:class => 'form-control'}) %>
  <%= geographic.collection_select(:state, Geographic.select(:state).uniq, :state, :state,{:include_blank => "Select State"}, {:class => 'form-control'}) %>
  <%= geographic.collection_select(:city, Geographic.select(:city).uniq, :city, :city,{:include_blank => "Select City"}, {:class => 'form-control'}) %>
</div>

app/views/shared/_login.html.erb
<%= form_for :user,:url =>  home_login_path ,:html => {:class => 'form-inline', :id => 'formLogin'} do |f| %>
  <div class="form-group">
    <%= f.email_field :email,{:class => 'form-control', :placeholder => t('user.email'), :required => true} %>
    <%= f.password_field :password,{:class => 'form-control', :placeholder => t('user.password'), :required => true} %>
    <%= f.submit t('buttons.login'),{:class => 'btn btn-success form-control'} %>
  </div>
<% end %>