config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Session controller routes for login and logout
  post 'home/login'
  get 'home/logout'

  root 'home#index'

  # Routes for Customers(users)
  get '/customers' => 'users#index'
  get '/customers/new' => 'users#new'
  post '/customers' => 'users#create'
  get '/customers/:id' => 'users#show'
  get '/customers/edit/:id' => 'users#edit'
  patch '/customers/:id' => 'users#update'
  delete '/customers/:id' => 'users#destroy'
  get '/customers', :controller => :users, :action => :index, :page => 1

  # Routes for Bulk Uploads
  get '/bulk_uploads/customers'
  get '/bulk_uploads/credit_cards'
  get '/bulk_uploads/transactions'
  post '/bulk_uploads/upload' => 'bulk_uploads#upload'

  # Resourceful Routes
  resources :users
  resources :transactions
  resources :statements
  resources :bulk_uploads
  resources :credit_cards

  # temp route to create admin
  get '/create_admin' => 'users#create_admin'

  # Other utility routes
  get '/find_geographic/:zip_code' => 'users#find_geographic'
  get '/find_states/:country' => 'users#get_states_from_country'
  get '/find_cities/:state' => 'users#get_cities_from_state'
  post '/customers/filter' => 'users#filter_values'
  get 'credit_cards_of_user/:user_id' => 'credit_cards#user_credit_cards'
  # post '/sort' => 'datatables#sort_array'
  post '/filter' => 'datatables#sort_array'

  get '/generate_customer_id' => 'migration#generate_customer_id'

  post '/upload/file' => 'users#file_upload'

  get '/pdf' => 'statements#create_statement_template'
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Credit Card Portal</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="layout-body">
    <div class="container-fluid">
      <div class="row" id="main-header">
        <div class="col-md-6">
          <img class="logo" src="/assets/aimdek-logo.png"/>
          <h1 id="appName" style="display:inline-block;">Credit Card Application</h1>
        </div>
        <div class="col-md-6">
          <% if session[:user_id].nil? %>
            <div class="col-md-9 col-md-offset-3">
              <%= render 'shared/login' %>
              <% if notice %>
                <div class="alert alert-danger notice">
                  <%= flash[:notice] unless flash[:notice].blank? %>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="col-md-7 col-md-offset-5">
              <% if notice %>
                <div class="alert alert-success notice">
                  <%= flash[:notice] unless flash[:notice].blank? %>
                </div>
              <% end %>
              <h4>
                <%= "#{t('messages.welcome')}," %>
                <%= User.find(session[:user_id]).full_name unless session[:user_id].blank? %>
                <%= link_to t('buttons.logout'),  home_logout_path , :class => 'btn btn-danger btn-sm' %>
              </h4>
            </div>
          <% end %>
        </div>
      </div>
      <% if !session[:user_id].blank? %>
        <div class="container">
          <ul class="nav nav-pills nav-justified navigation-bar">
            <li class="active" role="presentation">
              <a href="#" onclick="window.location.href='/'">
                <%= t('navigation_labels.home') %>
              </a>
            </li>
            <li role="presentation">
              <a href="#" onclick="window.location.href='<%= customers_path %>'">
                <%= t('navigation_labels.customers') %>
              </a>
            </li>
            <li role="presentation">
              <a href="#" onclick="window.location.href='<%= statements_path %>'">
                <%= t('navigation_labels.statements') %>
              </a>
            </li>
            <li role="presentation">
              <a href="#" onclick="window.location.href='<%= transactions_path %>'">
                <%= t('navigation_labels.transactions') %>
              </a>
            </li>
            <li role="presentation">
              <a href="#" onclick="window.location.href='<%= bulk_uploads_path %>'">
                <%= t('navigation_labels.bulk_uploads') %>
              </a>
            </li>
          </ul>
        </div>
      <% end %>
      <div class="container margin-top-20">
        <%= yield %>
      </div>
    </div>
    <footer>
      <h5>© 2015 AIMDek Technologies. All rights reserved.</h5>
    </footer>
  </body>
</html>